name: Called Workflow
on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      notify:
        type: boolean
        default: false

jobs:  # This is the missing part that wraps your job definition
  run:
    runs-on: ubuntu-22.04
    environment: ${{ github.event.inputs.env }}
    steps:
      - name: Called Workflow
        run: echo "Called Workflow"
      
      - name: Notify
        if: ${{ github.event.inputs.notify }}
        run: echo "Notify"
